### ISSUE TITLE
Output file fixes

### ISSUE THREAD

**Issue by TomMaullin** [TomMaullin/BLM-py#71]
As discussed in PR #65 :

* Filenames should be able to be specified _without_ extension... so you're not dependent on whether the images happen to be `.nii`, `.nii.gz` or `.{hdr,img}`.  Might need nibabel's `filename_parser`.
* To avoid an explosion of files, consider saving `blm_vox_cov*` files as 4D file.  Also, _any_ file that you number, use at least 2 digits padded by zeros.

**Comment by TomMaullin** [comment]
I aim to address this issue this week.

**Comment by TomMaullin** [comment]
Hi @nicholst ,

I just wanted to confirm what the code should do when there are two files with the same name but different extensions. E.g. In a directory there are the files:

```
example.nii
example.nii.gz
example.hdr
```

And the user just enters `example` as input (i.e. without the extension). Should it choose a file arbitrarily from the 3?

**Comment by nicholst** [comment]
Argh… I was hoping that nibabel had a automatic / sophisticated way of dealing with this… Ug.

OK, here’s a simple practical solution:

1. Use file name as given; *if* doesn’t exist go to 2
2. If the extension *isn’t* one of: 

'.nii.gz', '.nii', '.hdr.gz', '.hdr’, '.img.gz', '.img’ 

try opening the file by adding one of the following extensions, in this order...

'.nii.gz', '.nii', '.img.gz', '.img’

… stopping when first one is found.

3. If the file has no known extension, or none of the added extensions exists, FAIL.

The Nibabel filename_parser can help with part #2.

Does this make sense?

Arrrgh… now that I look back at it this looks like a lot of effort for something basic.  An alternative implementation is just:

1. Use filename as given; if it doesn’t exist go to 2
2. If extension *isn’t* '.nii.gz', try opening with that extension.

This is because the .nii.gz is the most common extension.

**Comment by TomMaullin** [comment]
This issue has now been resolved in PR #78.
